# Generated by Django 4.0 on 2024-01-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('giturl', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
